### ISSUE TITLE
Token & Download

### ISSUE THREAD

**Issue by CodersPress** [radishconcepts/WordPress-GitHub-Plugin-Updater#72]
When do you think you might release 1.7?

I need some kind of token_access or I'll get penalized on API attempts - Any idea which I should be choosing for a PUBLIC REPO ?

repo
repo:status
repo_deployment
public_repo
delete_repo
user
user:email
user:follow
admin:org
write:org
read:org
admin:public_key
write:public_key
read:public_key
admin:repo_hook
write:repo_hook
read:repo_hook
admin:org_hook
gist
notifications

**Comment by afragen** [comment]
repo and public_repo are all that is really needed here. That's what I'm using in GitHub Updater.

**Comment by CodersPress** [comment]
Thanks for the reply...

Seems leaving everything unchecked is just as good... it becomes public_access

Note: I was unable to select both repo and public_repo it defaulted to just repo

Also with just public_repo selected I was emailed a (warning) notice that my access_key wasn't safe and i was deactivated.

==================

We noticed that a valid OAuth access token of yours was committed to a public GitHub repository, xxxxxxxx/xxxxxxx. Publicly disclosing a valid access token would allow other people to interact with GitHub on your behalf, potentially altering data, your contact information, and billing data.

As a precautionary measure, we have revoked the OAuth token. A new token will need to be generated in order to continue using OAuth to authenticate to GitHub. Here are a couple of steps you can do to ensure your account security has not been compromised:

* Review any unauthorized OAuth applications, and remove any you don't recognize: https://help.github.com/articles/keeping-your-ssh-keys-and-application-access-tokens-safe/#reviewing-your-authorized-applications-oauth
* Review you security log to ensure that no other malicious activity has occured: https://help.github.com/articles/reviewing-your-security-log/

Please feel free to contact us at support@github.com if you have any questions or concerns.

Thanks,
GitHub.com

**Comment by afragen** [comment]
Did you accidentally set this for a particular repo and not under personal settings?

**Comment by CodersPress** [comment]
Settings -> Personal Access Tokens -> Generate new token...

I just gave it a name and pasted that key to my plugin config?

**Comment by afragen** [comment]
It's not the name you use, it's the actual token.

**Comment by afragen** [comment]
https://github.com/settings/tokens/new

**Comment by CodersPress** [comment]
Yeah I know the key - the Token Key -eg: 46565jk46h45hk6hk45jh654jk654kj6h45h6h45k

I meant I just give it a Description (Name) 

Anyway not to worry about that... its fine just leaving all un-ticked. 

Any ideas about this : https://github.com/radishconcepts/WordPress-GitHub-Plugin-Updater/issues/73

**Comment by afragen** [comment]
Actually, yes. I sent you an email.
