### ISSUE TITLE
Add composer.json

### ISSUE THREAD

**Issue by helgatheviking** [radishconcepts/WordPress-GitHub-Plugin-Updater#86]
Could this have a composer.json and be submitted to packagist.org so we could include it as a dependency in our own plugins?

**Comment by helgatheviking** [comment]
Oops... good catch. I think composer then?

**Comment by jazzsequence** [comment]
Yep. Just submitted a PR to add a Composer file. 😄 
Someone will still need to submit it to Packagist, and ideally that should be @radishconcepts, being the maintainer, but it should be set up for that.

**Comment by uprise10** [comment]
Hi all, just merged the PR, and added the package to Packagist. Hope you can move forward now!

https://packagist.org/packages/radishconcepts/wordpress-github-plugin-updater
